#!/usr/bin/env bash
# Script that will display information about subdomains
DOMAIN="$1"
SUBDOMAIN="$2"

if [ "$#" -eq 1 ]
then
	for subdomains in "www" "lb-01" "web-01" "web-02"
	do
		A=$(dig $subdomains.$DOMAIN | grep -A1 'ANSWER SECTION:' | tail -n 1 | awk '{ print $4 }')
		IP=$(dig $subdomains.$DOMAIN | grep -A1 'ANSWER SECTION:' | tail -n 1 | awk '{ print $5 }')
		echo "The subdomain $subdomains is a $A record and points to $IP"
	done
elif [ "$#" -eq 2 ]
then
	A=$(dig $SUBDOMAIN.$DOMAIN | grep -A1 'ANSWER SECTION:' | tail -n 1 | awk '{ print $4 }')
	IP=$(dig $SUBDOMAIN.$DOMAIN | grep -A1 'ANSWER SECTION:' | tail -n 1 | awk '{ print $5 }')
	echo "The subdomain $SUBDOMAIN is a $A record and points to $IP"
fi

