#!/usr/bin/env bash
# This script is configureing your Nginx server to have a custom 404 page that contains the string Ceci n'est pas une page
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'

echo "Hello World" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/error404.html

new_page="https://www.youtube.com/watch?v=QH2-TGUlwu4"
file="/etc/nginx/sites-available/default"

sudo sed -i "/listen 80 default_server/a rewrite ^/redirect_me $new_page permanent;" $file
sudo sed -i "/listen 80 default_server/a error_page 404 /error404.html;" $file

sudo service nginx restart
